### ISSUE TITLE
为什么运行完import hydrodataset没有./hydrodataset?

### ISSUE THREAD

**Issue by zhending111** [OuyangWenyu/hydrodataset#11]
您好，我这个问题该如何解决？

**Comment by LiTianliDUT** [comment]
hydrodataset 属于我们单独配置的环境，在使用之前需要先进行安装。
在HYDRODATASET文件夹下找到env-dev.yml文件，即我们所需安装的内容。
具体安装步骤：1.在HYDRODATASET文件夹下打开终端
                          2.输入 `conda env create -f env-dev.yml  `
                          3.等待安装完毕即可。
安装完成后，可通过输入` conda activate hydrodataset `，测试是否安装成功，并激活环境。

**Comment by LiTianliDUT** [comment]
> hydrodataset 属于我们单独配置的环境，在使用之前需要先进行安装。 在HYDRODATASET文件夹下找到env-dev.yml文件，即我们所需安装的内容。 具体安装步骤：1.在HYDRODATASET文件夹下打开终端 2.输入 `conda env create -f env-dev.yml ` 3.等待安装完毕即可。 安装完成后，可通过输入`conda activate hydrodataset`，测试是否安装成功，并激活环境。

如果并不是在vscode上激活环境，而是选择在windows中直接使用cmd激活环境，需要先移动到env-dev.yml文件所在位置。
右键点击YAML文件，选择复制文件地址。
在cmd中输入`cd <文件地址>`
再按照上述具体安装步骤运行即可。

**Comment by zhending111** [comment]
谢谢老师，我直接把路径写在代码里了，已解决
