### ISSUE TITLE
下载数据失败

### ISSUE THREAD

**Issue by KiltAB** [OuyangWenyu/hydrodataset#5]
作者您好，还是想请教一下，为什么通过提供的路径下载数据总是失败，下载数据总是受损，然后利用calms下载的时候，将download设置为TRUE时，会报错说是str没有pathjoin

**Comment by OuyangWenyu** [comment]
下载数据还是手动下载吧，之前写第一个版本的时候下载很慢，然后后续就没有再针对更新了，会有一些问题，手动下载数据按照readme展示的文件夹组织，就行

**Comment by KiltAB** [comment]
感谢解答，手动下载的话是下载这个zip么，可是这个完全下不动啊
![image](https://github.com/OuyangWenyu/hydrodataset/assets/99948662/fd7c88c3-572d-42d8-9740-5776110f2cb5)

**Comment by KiltAB** [comment]
用python脚本也是，下载的数据是损坏的

**Comment by KiltAB** [comment]
我试着分开下载，但是这些稍微大点的压缩包依然下不动，挂vpn也是，还有没有什么别的下载方式呢
![image](https://github.com/OuyangWenyu/hydrodataset/assets/99948662/27e46071-04be-4633-8ad9-41e8b52b87e2)

**Comment by KiltAB** [comment]
或者说这些数据有百度网盘或者谷歌云盘之类的方便分享一下么

**Comment by OuyangWenyu** [comment]
https://www.kaggle.com/datasets/headwater/camels  这有一个处理成nc格式的 你可以看看满足不满足需求 读取代码也在这个repo里有。
https://www.kaggle.com/datasets/hydroowen/susquehanna-data 这里也有一部分CAMELS的数据，但不全
