### ISSUE TITLE
关于hydrodataset

### ISSUE THREAD

**Issue by KiltAB** [OuyangWenyu/hydrodataset#6]
我在导入hydrodataset这个包后，会报出一个DEBUG，说是module ‘forge’ has no attribute 'copy',这个正常么，copy应该是python自带的一个包，是因为其他地方有重名的函数么？
![c0a97638db2a63337b4acca0e870cb7](https://github.com/OuyangWenyu/hydrodataset/assets/99948662/4c58ccaa-94e6-4d2a-872a-258ae2bb3ce5)

**Comment by OuyangWenyu** [comment]
这应该没报错吧  DEBUG 那些是一些logging的输出  只要没有ERROR 可以不管
